name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install pnpm (corepack method)
        run: |
          # First try corepack (comes with Node.js 16+)
          corepack enable
          corepack prepare pnpm@8 --activate
          
          # Verify installation
          if ! command -v pnpm &> /dev/null; then
            echo "::warning::Corepack method failed, falling back to npm install"
            npm install -g pnpm@8
            echo "Adding pnpm to PATH: $(npm root -g)/bin"
            echo "$(npm root -g)/bin" >> $GITHUB_PATH
          fi

      - name: Verify pnpm installation
        run: |
          echo "Checking pnpm installation..."
          which pnpm || echo "::error::pnpm still not found in PATH"
          pnpm --version || (echo "::error::pnpm command failed" && exit 1)
          echo "PATH: $PATH"
          echo "Global node_modules: $(npm root -g)"

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm run turbo:lint

      - name: Run tests
        run: pnpm run turbo:test

      - name: Build all apps
        run: pnpm run turbo:build

  deploy:
    needs: test_and_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install pnpm (corepack method)
        run: |
          corepack enable
          corepack prepare pnpm@8 --activate
          if ! command -v pnpm &> /dev/null; then
            npm install -g pnpm@8
            echo "$(npm root -g)/bin" >> $GITHUB_PATH
          fi

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Build project
        run: pnpm run turbo:build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel@latest
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} \
            --scope ${{ secrets.VERCEL_SCOPE }} \
            --yes