name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install and Activate pnpm
        run: |
          # Enable Corepack (built into Node.js)
          corepack enable
          # Install and activate pnpm
          corepack prepare pnpm@8 --activate
          # Verify installation
          echo "PNPM version: $(pnpm --version)"
          echo "PNPM path: $(which pnpm)"

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm run turbo:lint

      - name: Run tests
        run: pnpm run turbo:test

      - name: Build all apps
        run: pnpm run turbo:build

  deploy:
    needs: test_and_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install and Activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8 --activate
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run turbo:build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel@latest
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} \
            --scope ${{ secrets.VERCEL_SCOPE }} \
            --yes