name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm globally
        run: npm install -g pnpm@8

      - name: Verify pnpm installation
        run: |
          echo "PNPM version: $(pnpm --version)"
          echo "PNPM path: $(which pnpm)"
          echo "Adding pnpm to PATH"
          echo "$(npm root -g)/pnpm/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm run turbo:lint

      - name: Run tests
        run: pnpm run turbo:test

      - name: Build all apps
        run: pnpm run turbo:build

  deploy:
    needs: test_and_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 🔥 SAME FIX FOR DEPLOY JOB
      - name: Install pnpm globally
        run: npm install -g pnpm@8

      - name: Verify pnpm installation
        run: |
          echo "PNPM version: $(pnpm --version)"
          echo "PNPM path: $(which pnpm)"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run turbo:build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} \
            --confirm --org ${{ secrets.VERCEL_ORG_ID }} \
            --project ${{ secrets.VERCEL_PROJECT_ID }}